# -*- coding: utf-8 -*-
"""RNA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VpC8Tc3YvvdDk6l6XvGteL76JsKJ1l4J
"""

import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

acertos = 0
erros = 0
GG = []
AA = []
GE = []
AE = []

data = pd.read_csv('./drive/MyDrive/FATEC/teste.csv')  
data2 = pd.read_csv('./drive/MyDrive/FATEC/treino.csv') 




X_test = data[['Vmag', 'B-V', 'Amag']]  
y_test = data['TargetClass'] 
X_train = data2[['Vmag', 'B-V', 'Amag']]  
y_train = data2['TargetClass']

model = Sequential()
model.add(Dense(64, activation='relu', input_dim=3))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10, batch_size=32)

loss, accuracy = model.evaluate(X_test, y_test)
# Fazer previsões nos dados de teste
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)  

for i in range(len(y_pred)):
    if y_pred[i] == y_test.iloc[i]:
        if(y_pred[i] == 0):
          AA.append(1)
        else:
          GG.append(1)
        acertos += 1
    else:
        if(y_pred[i] == 1):
          AE.append(1)
        else:
          GE.append(1)
        erros += 1



print('\n-----------------------------------------------------------')
print('\nTotal: ', len(y_test),'\nAcertos: ', acertos, '\nErros: ', erros)
print('\nMATRIZ DE CONFUSÃO:\n')
print('      Anã | Gigante')
print('Anã: ', len(AA), '|', len(AE))
print('Gig: ', len(GE), ' |' , len(GG))
print('\nErros:', loss)
print('Acurácia:', accuracy)